Fix typo in refresh_equipment
w1ll1am23/pyeconet pull request #29
Opened 2023-01-10 01:22 UTC by xavierd

Reading the code, I noticed that an undefined method was being called.

2023-04-05 23:27 UTC, CodingSquirrel requested changes
@w1ll1am23 Can we get some eyes on this PR? Home assistant integration calls this function to refresh values hourly, but it currently does nothing. @xavierd 's and my changes should fix that.

2023-04-05 23:27 UTC, CodingSquirrel commented on src/pyeconet/api.py
>                  equipment = self._equipment.get(_equip.get("device_name", ""), None)
```suggestion
                serial = _equip.get("serial_number")
                equipment = self._equipment.get(serial)
```

`device_name` isn't the key for equipment, `serial_number` is. That explains why the below typo never throws for trying to call a non-existent function.

2023-04-05 23:35 UTC, w1ll1am23 commented
Nice! Good catch. Assuming y'all have tested this and its all working? I don't have the capacity to test it now, but I can get this merged and get a fix version out there.

2023-04-05 23:52 UTC, CodingSquirrel commented
I didn't do a full test, just checked some of the lines in a terminal to check the keys matched serial, and double checked reading over the code. If you'd prefer better testing before merging I can do some more thorough testing.

2023-04-05 23:54 UTC, w1ll1am23 commented
Ehh we can merge it, doesn't break anything until someone bumps the Home Assistant version.

Is the change on the HA side something one of you will be opening? If so, you can just test it out when making that change.

2023-04-05 23:59 UTC, merged

2023-04-06 00:01 UTC, CodingSquirrel commented
I think my suggested change got left out of the merged change. I can submit as a separate PR.

2023-04-06 00:02 UTC, w1ll1am23 commented
Ugh sorry yeah I forgot you left that comment my bad shouldn't have been looking at that on mobile.